<?php

namespace ContainerOyWyfRi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Tkffvk1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tkffvk1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tkffvk1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reclamationRepository' => ['privates', '.errored.z1rOsfI', NULL, 'Cannot determine controller argument for "App\\Controller\\ReclamationController::new()": the $reclamationRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\ReclamationRepository".'],
        ], [
            'reclamationRepository' => '?',
        ]);
    }
}
