<?php

namespace ContainerOyWyfRi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0NP03bDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0NP03bD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0NP03bD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'exercice' => ['privates', '.errored..service_locator.0NP03bD.App\\Entity\\Exercice', NULL, 'Cannot autowire service ".service_locator.0NP03bD": it needs an instance of "App\\Entity\\Exercice" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'exercice' => 'App\\Entity\\Exercice',
        ]);
    }
}
