<?php

namespace ContainerOyWyfRi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Z1rOsfIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.z1rOsfI' shared service.
     *
     * @return \App\Repository\ReclamationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ReclamationController::new()": the $reclamationRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\ReclamationRepository".');
    }
}
