<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOyWyfRi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOyWyfRi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOyWyfRi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOyWyfRi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOyWyfRi\App_KernelDevDebugContainer([
    'container.build_hash' => 'OyWyfRi',
    'container.build_id' => '0b1b087e',
    'container.build_time' => 1740088347,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOyWyfRi');
